version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "uv"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      prod-dependencies:
        dependency-type: "production"
      dev-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "wagtail"
        # only allow x.y.* updates from dependabot for this package
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "django"
        # only allow x.y.* updates from dependabot for this package
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
